# Generated by Django 5.2.7 on 2025-11-09 23:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IdCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('IdIngrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_de_medida', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('IdMesa', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroMesa', models.IntegerField(unique=True)),
                ('Capacidad', models.IntegerField(default=4)),
                ('Ocupada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Mesa',
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('IdPlatillo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Platillo',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('IdProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('IdPedido', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('MontoTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('MetodoPago', models.CharField(blank=True, max_length=50, null=True)),
                ('IdCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.cliente')),
                ('IdMesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='He_Sai_Mali.mesa')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido_Platillo',
            fields=[
                ('IdPedido_Platillo', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(choices=[('Registrado', 'Registrado'), ('Listo', 'Listo'), ('Servido', 'Servido'), ('Facturado', 'Facturado')], default='Registrado', max_length=20)),
                ('Cantidad', models.IntegerField(default=1)),
                ('IdPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='He_Sai_Mali.pedido')),
                ('IdPlatillo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='He_Sai_Mali.platillo')),
            ],
            options={
                'db_table': 'Pedido_Platillo',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('IdEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('Cedula', models.CharField(max_length=16, unique=True)),
                ('Rol', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Platillo_Ingrediente',
            fields=[
                ('IdPlatillo_Ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdIngrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='He_Sai_Mali.ingrediente')),
                ('IdPlatillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.platillo')),
            ],
            options={
                'db_table': 'Platillo_Ingrediente',
                'unique_together': {('IdPlatillo', 'IdIngrediente')},
            },
        ),
        migrations.CreateModel(
            name='Ingrediente_Proveedor',
            fields=[
                ('IdIngrediente_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('IdIngrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.ingrediente')),
                ('IdProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.proveedor')),
            ],
            options={
                'db_table': 'Ingrediente_Proveedor',
                'unique_together': {('IdIngrediente', 'IdProveedor')},
            },
        ),
        migrations.CreateModel(
            name='Empleado_Pedido',
            fields=[
                ('IdEmpleado_Pedido', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAsignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('IdPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendido_por', to='He_Sai_Mali.pedido')),
                ('IdEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Empleado_Pedido',
                'unique_together': {('IdEmpleado', 'IdPedido')},
            },
        ),
    ]
