# Generated by Django 5.2.7 on 2025-11-14 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloInventario',
            fields=[
                ('idArticuloInventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_de_medida', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ArticuloInventario',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCliente', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('idMesa', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
                ('ocupada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Mesa',
            },
        ),
        migrations.CreateModel(
            name='ProductoMenu',
            fields=[
                ('idProductoMenu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(max_length=20)),
                ('receta', models.CharField(max_length=1000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'ProductoMenu',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('montoTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodoPago', models.CharField(blank=True, max_length=50, null=True)),
                ('estadoDePago', models.BooleanField(default=False)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.cliente')),
                ('idMesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='He_Sai_Mali.mesa')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido_ProductoMenu',
            fields=[
                ('idPedido_ProductoMenu', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Registrado', 'Registrado'), ('Listo', 'Listo'), ('Servido', 'Servido'), ('Facturado', 'Facturado')], default='Registrado', max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='He_Sai_Mali.pedido')),
                ('idProductoMenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='He_Sai_Mali.productomenu')),
            ],
            options={
                'db_table': 'Pedido_ProductoMenu',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=60)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('cedula', models.CharField(max_length=16, unique=True)),
                ('rol', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='ProductoMenu_ArticuloInventario',
            fields=[
                ('idProductoMenu_ArticuloInventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idArticuloInventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='He_Sai_Mali.articuloinventario')),
                ('idProductoMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.productomenu')),
            ],
            options={
                'db_table': 'ProductoMenu_ArticuloInventario',
                'unique_together': {('idProductoMenu', 'idArticuloInventario')},
            },
        ),
        migrations.CreateModel(
            name='ArticuloInventario_Proveedor',
            fields=[
                ('idArticuloInventario_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ultimaFechaCompra', models.DateTimeField(default=django.utils.timezone.now)),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idArticuloInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.articuloinventario')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.proveedor')),
            ],
            options={
                'db_table': 'ArticuloInventario_Proveedor',
                'unique_together': {('idArticuloInventario', 'idProveedor')},
            },
        ),
        migrations.CreateModel(
            name='Empleado_Pedido',
            fields=[
                ('idEmpleado_Pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAsignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.pedido')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Empleado_Pedido',
                'unique_together': {('idEmpleado', 'idPedido')},
            },
        ),
    ]
