# Generated by Django 5.2.7 on 2025-11-05 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('IdPedido', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('MontoTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('MetodoPago', models.CharField(blank=True, max_length=50, null=True)),
                ('IdPersona', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('IdPlatillo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
                'db_table': 'Platillo',
            },
        ),
        migrations.CreateModel(
            name='Empleado_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAsignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('IdEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('IdPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendido_por', to='He_Sai_Mali.pedido')),
            ],
            options={
                'verbose_name': 'Asignación de Empleado a Pedido',
                'verbose_name_plural': 'Asignaciones de Empleados a Pedidos',
                'db_table': 'Empleado_Pedido',
                'unique_together': {('IdEmpleado', 'IdPedido')},
            },
        ),
        migrations.CreateModel(
            name='Pedido_Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(choices=[('Registrado', 'Registrado'), ('Listo', 'Listo para servir'), ('Servido', 'Servido'), ('Facturado', 'Facturado')], default='Registrado', max_length=20)),
                ('Cantidad', models.IntegerField(default=1)),
                ('IdPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='He_Sai_Mali.pedido')),
                ('IdPlatillo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='He_Sai_Mali.platillo')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
                'db_table': 'Pedido_Platillo',
                'unique_together': {('IdPedido', 'IdPlatillo')},
            },
        ),
    ]
