# Generated by Django 5.2.7 on 2025-11-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='idMesa',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
