# Generated by Django 5.2.7 on 2025-11-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0002_alter_mesa_idmesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomenu',
            name='receta',
        ),
        migrations.AddField(
            model_name='productomenu',
            name='tiempoPreparacion',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido_productomenu',
            name='idProductoMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.productomenu'),
        ),
        migrations.AlterField(
            model_name='productomenu_articuloinventario',
            name='idArticuloInventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='He_Sai_Mali.articuloinventario'),
        ),
    ]
