# Generated by Django 5.2.7 on 2026-06-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0003_remove_productomenu_receta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_factura',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada')], default='VIGENTE', max_length=10, verbose_name='Estado de la Factura'),
        ),
    ]
