# Generated by Django 5.2.7 on 2026-06-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0004_pedido_estado_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaAlertasStock',
            fields=[
                ('id', models.IntegerField(db_column='idArticuloInventario', primary_key=True, serialize=False)),
                ('ingrediente', models.CharField(max_length=100)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_de_medida', models.CharField(max_length=20)),
                ('porciones_posibles', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_alertas_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaPedidosCocina',
            fields=[
                ('id', models.IntegerField(db_column='idPedido_ProductoMenu', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_pedido', models.IntegerField(db_column='idPedido_id')),
                ('nombre_platillo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('id_mesa', models.IntegerField(db_column='idMesa_id', null=True)),
            ],
            options={
                'db_table': 'vw_pedidos_cocina',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='pedido_productomenu',
            name='estado',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('Listo', 'Listo'), ('Servido', 'Servido'), ('Facturado', 'Facturado'), ('Merma', 'Merma'), ('Anulado', 'Anulado')], default='Registrado', max_length=20),
        ),
    ]
