# Generated by Django 5.2.7 on 2026-07-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0006_auditoria_mesa_sucursal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria_mesa',
            name='usuario_responsable',
        ),
        migrations.AddField(
            model_name='auditoria_mesa',
            name='rol',
            field=models.CharField(default='Sistema', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditoria_mesa',
            name='usuario',
            field=models.CharField(default='Sistema', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoria_mesa',
            name='accion',
            field=models.CharField(max_length=30),
        ),
    ]
