# Generated by Django 5.2.7 on 2026-07-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0007_remove_auditoria_mesa_usuario_responsable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='nombre',
            new_name='nombre_comercial',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='direccion',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='direccion_exacta',
            field=models.TextField(default='Ciudad Sandino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='estado_operativo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cerrado', 'Cerrado'), ('Mantenimiento', 'En Mantenimiento')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='municipio',
            field=models.CharField(default='Ciudad Sandino', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero_matricula_municipal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero_ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
