# Generated by Django 5.2.7 on 2026-07-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0008_rename_nombre_sucursal_nombre_comercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='estado_operativo',
        ),
    ]
