# Generated by Django 5.2.7 on 2026-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0009_remove_sucursal_estado_operativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria_mesa',
            name='sucursal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
