# Generated by Django 5.2.7 on 2026-07-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0010_auditoria_mesa_sucursal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria_mesa',
            name='empleado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
