# Generated by Django 5.2.7 on 2026-07-30 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0011_auditoria_mesa_empleado_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaGeneral',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_id', models.IntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('sucursal_id', models.IntegerField(blank=True, null=True)),
                ('modulo', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=30)),
                ('detalles', models.TextField()),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AuditoriaGeneral',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.DeleteModel(
            name='Auditoria_Mesa',
        ),
    ]
