# Generated by Django 5.2.7 on 2026-07-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0012_auditoriageneral_delete_auditoria_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarticuloinventario_proveedor',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalarticuloinventario_proveedor',
            name='idArticuloInventario',
        ),
        migrations.RemoveField(
            model_name='historicalarticuloinventario_proveedor',
            name='idProveedor',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalempleado',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalempleado',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='idCliente',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='idMesa',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='historicalpedido_productomenu',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpedido_productomenu',
            name='idPedido',
        ),
        migrations.RemoveField(
            model_name='historicalpedido_productomenu',
            name='idProductoMenu',
        ),
        migrations.RemoveField(
            model_name='historicalproductomenu',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductomenu_articuloinventario',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductomenu_articuloinventario',
            name='idArticuloInventario',
        ),
        migrations.RemoveField(
            model_name='historicalproductomenu_articuloinventario',
            name='idProductoMenu',
        ),
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalArticuloInventario',
        ),
        migrations.DeleteModel(
            name='HistoricalArticuloInventario_Proveedor',
        ),
        migrations.DeleteModel(
            name='HistoricalCliente',
        ),
        migrations.DeleteModel(
            name='HistoricalEmpleado',
        ),
        migrations.DeleteModel(
            name='HistoricalPedido',
        ),
        migrations.DeleteModel(
            name='HistoricalPedido_ProductoMenu',
        ),
        migrations.DeleteModel(
            name='HistoricalProductoMenu',
        ),
        migrations.DeleteModel(
            name='HistoricalProductoMenu_ArticuloInventario',
        ),
        migrations.DeleteModel(
            name='HistoricalProveedor',
        ),
    ]
