# Generated by Django 5.2.7 on 2026-08-14 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Sai_Mali', '0013_remove_historicalarticuloinventario_proveedor_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloinventario',
            name='tipoArticulo',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='articuloinventario_proveedor',
            name='fechaCompra',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auditoriageneral',
            name='accion',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoriageneral',
            name='empleado_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriageneral',
            name='fecha_accion',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auditoriageneral',
            name='modulo',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditoriageneral',
            name='sucursal_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='ocupada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_factura',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada')], db_index=True, default='VIGENTE', max_length=10, verbose_name='Estado de la Factura'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido_productomenu',
            name='estado',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('Listo', 'Listo'), ('Servido', 'Servido'), ('Facturado', 'Facturado'), ('Merma', 'Merma'), ('Anulado', 'Anulado')], db_index=True, default='Registrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='productomenu',
            name='categoria',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productomenu',
            name='disponible',
            field=models.BooleanField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='registrosesion',
            name='fecha_login',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
